"""Generate the ONE sweep JFH for the Phase-3 angle x distance study.

The plate is STATIONARY (target vehicles do not move): the visiting vehicle
is swept instead. For each firing the VV (single thruster at the VV origin,
no cant) is placed on the arc of radius L about the plate center
C = (4, 0, 0), with the thruster axis aimed at C and the JFH DCM set so the
pipeline's plume normal (first column of the DCM, with the identity TCF)
points along that axis.

Pose parametrization, all in the plate's tilt plane (global X-Z):

    d_hat(alpha) = cos(alpha) * n_hat + sin(alpha) * t_hat
    VV position  = C + L * d_hat(alpha),  thruster axis = -d_hat(alpha)

where n_hat = (-sin 60, 0, cos 60) is the plate normal facing the nozzle
side and t_hat = (cos 60, 0, sin 60) the plate's inclined tangent.
alpha = 0 is HEAD-ON (thruster axis along the plate normal; the paper's
alpha0 = 90 deg); the sign is the tilt direction, mapping
alpha_paper = 90 deg - |alpha|. Results must be mirror-symmetric in
+/-alpha (the plate is square); +/-90 deg is edge-on/degenerate and is
kept to confirm ~zero struck faces.

Sweep: alpha from -90 to +90 deg in 10 deg steps (19 angles) x
L/D in {2, 4, 6, 8, 10} (D = 1 m), enumerated distance-major:
firing index = i_L * 19 + i_alpha + 1. 95 firings total, firing time
1.0 s each.

JFH files are always generated by script, never hand-edited. Run from this
directory:  python generate_sweep_jfh.py
"""

from pathlib import Path

import numpy as np

from generate_jfh_inclined_plate import write_jfh

OUT_NAME = 'jfh_inclined_plate_sweep.A'

PLATE_CENTER = np.array([4.0, 0.0, 0.0])
ALPHA0_DEG = 60.0
ALPHAS_DEG = np.arange(-90.0, 90.0 + 1e-9, 10.0)
L_OVER_D = [2.0, 4.0, 6.0, 8.0, 10.0]


def pose_for(alpha_deg, L):
    """(vv_position, dcm) for one sweep firing; dcm's first column is the
    thruster axis (see the pipeline's plume-normal convention)."""
    a0 = np.deg2rad(ALPHA0_DEG)
    n_hat = np.array([-np.sin(a0), 0.0, np.cos(a0)])
    t_hat = np.array([np.cos(a0), 0.0, np.sin(a0)])
    alpha = np.deg2rad(alpha_deg)
    d_hat = np.cos(alpha) * n_hat + np.sin(alpha) * t_hat
    position = PLATE_CENTER + L * d_hat
    axis = -d_hat                       # aimed at the plate center
    # right-handed triad; the axis always lies in the X-Z plane, so the
    # global Y axis is a valid second column
    c1 = np.array([0.0, 1.0, 0.0])
    c2 = np.cross(axis, c1)
    dcm = np.column_stack([axis, c1, c2])
    return position, dcm


def dcm_string(dcm):
    return ' '.join(f'{v:.6e}' for v in np.asarray(dcm).ravel())


if __name__ == '__main__':
    firings = []
    for L in L_OVER_D:
        for alpha_deg in ALPHAS_DEG:
            position, dcm = pose_for(alpha_deg, L)
            firings.append((0.0, 1.0, dcm_string(dcm), tuple(position), [1]))
    out_path = Path(__file__).resolve().parent / OUT_NAME
    write_jfh(out_path, firings)
    print(f'saved {out_path} ({len(firings)} firings: '
          f'{len(ALPHAS_DEG)} angles x {len(L_OVER_D)} distances)')
