"""Phase-3 driver: angle x distance sweep of the Cai 2016 inclined plate.

Runs the 95-firing sweep JFH of case/plume/plume_inclined_plate (generated by
jfh/generate_sweep_jfh.py: VV on arcs of radius L about the stationary plate
center, thruster aimed at the center; alpha = 0 is head-on = paper
alpha0 = 90 deg, alpha_paper = 90 - |alpha| deg; L/D in {2, 4, 6, 8, 10})
through the strike pipeline's per-firing core, compute_plume_strikes -- the
same function PlumeStrikeEstimationStudy calls per firing -- keeping each
firing's per-face arrays separate so the pipeline's cumulative accumulation
never pollutes the per-pose analysis. This is a standalone study script:
nothing in pyrpod/mdao is used and nothing is optimized.

Outputs, to case/plume/plume_inclined_plate/results/sweep/ (gitignored):
  - sweep_coefficients.csv: per firing, the Eq.-15 plate-averaged
    coefficients CP/CF1/CF2/CQ/CM/s_cc from the pipeline AND from the exact
    reference (pyrpod/plume/CaiImpingement2016.py), plus the peak per-face
    Cp / |Cf| / Cq, struck-face counts, and per-firing wall time;
  - coeff_<name>.png: each averaged coefficient vs alpha, one curve per
    L/D, pipeline (solid + markers) and reference (dashed) on the same axes;
  - peaks.png: peak per-face pressure/shear/heat-flux coefficients vs alpha
    per L/D;
  - vtk/firing-<i>_a<alpha>_LoD<LD>.vtu: one VTK unstructured grid per
    firing (same writer as the other RPOD cases) carrying that pose's own
    per-face strikes, dimensional loads (pressure_Pa, shear_Pa,
    heat_flux_W_m2), and coefficients (Cp, Cshear, Cf1_case, Cf2_case, Cq).
    The Cf components here are in the mesh's CASE frame, un-flipped -- so
    the shear vectors point the way they physically do on that pose's
    mesh, unlike the paper-convention aggregate CF1/CM in the CSV. Written
    per firing (independent poses; no cumulative accumulation, unlike
    PlumeStrikeEstimationStudy.jfh_plume_strikes), so each file is exactly
    one pose. sweep_LoD<LD>.pvd ParaView collections group the
    fixed-distance poses with alpha as the time coordinate, so an angle
    sweep can be scrubbed in ParaView. Disable the VTK export with
    --no-vtk (CSV + plots only).

Conventions and sanity checks:
  - Averaged pipeline coefficients follow Eq. 15: area-weighted sums over
    the whole plate area S (unstruck faces carry zero load), with
    CM = sum(tau * Cp * A) / (2 * H0 * S) and s_cc = CM / CP.
  - The pipeline's per-face |shear| is decomposed onto the plate's
    (tau, s) axes along the tangential projection of the radial flow
    direction (the same decomposition as the Phase-1 figure overlays) to
    obtain signed Cf1/Cf2 comparable to the paper's components.
  - Poses with alpha < 0 map directly onto the paper geometry
    (tau_paper = tau_case); alpha > 0 is its mirror image, so CF1 and CM
    are sign-flipped into the paper convention. Mirror symmetry of the
    results in +/-alpha is then asserted (the plate is square).
  - +/-90 deg is edge-on/degenerate: the firings are kept (CSV rows and a
    printed report) but excluded from the plots and the mirror check. At
    exactly edge-on the facing test's surface_dot_plume is 0 in exact
    arithmetic, so the mesh's float32 normals make strike membership
    epsilon-arbitrary (a third to two thirds of the faces pass, not
    mirror-symmetrically). The plate-AVERAGED load there is ~zero as
    expected (a few percent of head-on), but individual epsilon-passing
    faces next to the in-plane nozzle carry large grazing near-field
    values at close range (peak Cp ~ 4 at L/D = 2), which would dominate
    the peak plots meaninglessly. (The reference at alpha_paper = 0
    likewise keeps only the small plume-spread load.)

Run from the repo root:  python scripts/inclined_plate_sweep_study.py
(add --no-vtk to skip the per-pose VTK export).
"""

import argparse
import csv
import sys
import time
from pathlib import Path

import numpy as np

_REPO_ROOT = Path(__file__).resolve().parents[1]
for extra in (_REPO_ROOT, _REPO_ROOT / 'tests' / 'plume'):
    if str(extra) not in sys.path:
        sys.path.insert(0, str(extra))

import matplotlib  # noqa: E402
matplotlib.use('Agg')
import matplotlib.pyplot as plt  # noqa: E402

import plume_impingement_utils as piu  # noqa: E402  (paper constants)
from pyrpod.mission import MissionEnvironment  # noqa: E402
from pyrpod.plume import CaiImpingement2016 as cai  # noqa: E402
from pyrpod.plume.PlumeStrikeCalculator import (  # noqa: E402
    compute_face_centroids,
    compute_plume_strikes,
)
from pyrpod.rpod import JetFiringHistory  # noqa: E402
from pyrpod.util.stl.stl import convert_stl_to_vtk  # noqa: E402
from pyrpod.vehicle import TargetVehicle, VisitingVehicle  # noqa: E402

CASE_DIR = str(_REPO_ROOT / 'case' / 'plume' / 'plume_inclined_plate') + '/'
SWEEP_JFH = 'jfh_inclined_plate_sweep.A'
RESULTS_DIR = Path(CASE_DIR) / 'results' / 'sweep'
VTK_DIR = RESULTS_DIR / 'vtk'

PLATE_CENTER = np.array([4.0, 0.0, 0.0])
ALPHA0_DEG = 60.0                       # the mesh's fixed global tilt
H_0 = W_0 = 4.0                         # plate semi-lengths (m)
ALPHAS_DEG = np.arange(-90.0, 90.0 + 1e-9, 10.0)
L_OVER_D = [2.0, 4.0, 6.0, 8.0, 10.0]

# dataviz categorical palette, fixed slot order (validated CVD-safe)
PALETTE = ['#2a78d6', '#008300', '#e87ba4', '#eda100', '#1baf7a']

_A0 = np.deg2rad(ALPHA0_DEG)
NORMAL_OUT = np.array([-np.sin(_A0), 0.0, np.cos(_A0)])  # toward the VV side
TANGENT_TAU = np.array([np.cos(_A0), 0.0, np.sin(_A0)])
TANGENT_S = np.array([0.0, 1.0, 0.0])

COEFF_NAMES = ['CP', 'CF1', 'CF2', 'CQ', 'CM', 's_cc']


def load_case():
    jfh = JetFiringHistory.JetFiringHistory(CASE_DIR)
    jfh.config.set('jfh', 'jfh', SWEEP_JFH)  # sweep JFH, same case assets
    jfh.read_jfh()

    tv = TargetVehicle.TargetVehicle(CASE_DIR)
    tv.set_stl()

    vv = VisitingVehicle.VisitingVehicle(CASE_DIR)
    vv.set_thruster_config()
    vv.set_thruster_metrics()

    me = MissionEnvironment.MissionEnvironment(CASE_DIR)
    return jfh, tv, vv, me


def face_areas(vectors):
    v0, v1, v2 = vectors[:, 0], vectors[:, 1], vectors[:, 2]
    return 0.5 * np.linalg.norm(np.cross(v1 - v0, v2 - v0), axis=1)


def pipeline_row(result, centroids, normals, areas, tau_face, thruster_pos,
                 alpha_deg):
    """Eq.-15 averaged coefficients, peaks, and per-face field arrays from
    one firing. Returns (coeffs, peaks, face_fields); face_fields holds
    the case-frame per-face arrays for VTK (Cf1_case/Cf2_case un-flipped,
    matching the actual mesh, unlike the paper-convention aggregates)."""
    S_tot = float(np.sum(areas))
    Cp = result['pressures'] / piu.Q_DYN
    Csh = result['shear_stress'] / piu.Q_DYN
    Cq = result['heat_flux_rate'] / piu.Q_DYN_HEAT

    # signed shear components along the plate axes (tangential projection
    # of the radial flow direction, as in the Phase-1 overlays)
    rel = centroids - thruster_pos
    dist = np.linalg.norm(rel, axis=1)
    u_hat = rel / dist[:, None]
    n_in = -NORMAL_OUT
    cos_inc = u_hat @ n_in
    t_vec = u_hat - cos_inc[:, None] * n_in
    t_norm = np.linalg.norm(t_vec, axis=1)
    safe = t_norm > 1e-12
    t_hat = np.zeros_like(t_vec)
    t_hat[safe] = t_vec[safe] / t_norm[safe, None]
    Cf1 = Csh * (t_hat @ TANGENT_TAU)
    Cf2 = Csh * (t_hat @ TANGENT_S)

    flip = -1.0 if alpha_deg > 0 else 1.0   # into the paper convention
    CP = float(np.sum(Cp * areas) / S_tot)
    CF1 = flip * float(np.sum(Cf1 * areas) / S_tot)
    CF2 = float(np.sum(Cf2 * areas) / S_tot)
    CQ = float(np.sum(Cq * areas) / S_tot)
    CM = flip * float(np.sum(tau_face * Cp * areas) / (2.0 * H_0 * S_tot))
    s_cc = CM / CP if CP != 0.0 else float('nan')

    face_fields = {
        'strikes': result['strikes'],
        'pressure_Pa': result['pressures'],
        'shear_Pa': result['shear_stress'],
        'heat_flux_W_m2': result['heat_flux_rate'],
        'Cp': Cp,
        'Cshear': Csh,
        'Cf1_case': Cf1,
        'Cf2_case': Cf2,
        'Cq': Cq,
    }
    return ({'CP': CP, 'CF1': CF1, 'CF2': CF2, 'CQ': CQ, 'CM': CM,
             's_cc': s_cc},
            {'peak_Cp': float(np.max(Cp)), 'peak_Cshear': float(np.max(Csh)),
             'peak_Cq': float(np.max(Cq)),
             'n_struck': int(np.count_nonzero(result['strikes']))},
            face_fields)


def write_pose_vtk(target, face_fields, base_name):
    """Write one pose's per-face fields to VTK_DIR/<base_name>.vtu via the
    shared convert_stl_to_vtk writer (pyevtk needs C-contiguous float64)."""
    cell_data = {k: np.ascontiguousarray(v, dtype=np.float64)
                 for k, v in face_fields.items()}
    convert_stl_to_vtk(target, VTK_DIR, filename=base_name,
                       cellData=cell_data)


def write_pvd(path, entries):
    """ParaView collection grouping (timestep, relative_vtu_path) entries."""
    lines = ['<?xml version="1.0"?>',
             '<VTKFile type="Collection" version="0.1" '
             'byte_order="LittleEndian">', '  <Collection>']
    for timestep, rel_file in sorted(entries):
        lines.append(f'    <DataSet timestep="{timestep:g}" group="" '
                     f'part="0" file="{rel_file}"/>')
    lines += ['  </Collection>', '</VTKFile>']
    path.write_text('\n'.join(lines) + '\n', encoding='utf-8')


def reference_rows():
    """Exact Eq.-15 coefficients per (|alpha|, L), cached (mirror-invariant)."""
    cache = {}
    for L in L_OVER_D:
        for abs_alpha in sorted({abs(a) for a in ALPHAS_DEG}):
            alpha_paper = np.deg2rad(90.0 - abs_alpha)
            cache[(abs_alpha, L)] = cai.averaged_coefficients(
                piu.S_0, alpha_paper, piu.EPS, piu.R_0, L, W_0, H_0)
    return cache


def check_mirror_symmetry(rows):
    """Results must be mirror-symmetric in +/-alpha (paper convention).

    The +/-90 deg poses are excluded: their strike membership comes from
    float32-epsilon signs in the facing test, which are not mirrored.
    CF2 is checked separately -- it vanishes identically by symmetry, so
    normalizing its asymmetry by its own (noise) scale is meaningless.
    """
    worst = 0.0
    for L in L_OVER_D:
        by_alpha = {r['alpha_deg']: r for r in rows if r['L_over_D'] == L
                    and abs(r['alpha_deg']) < 90.0}
        cp_scale = max(abs(r['CP_pipe']) for r in by_alpha.values())
        # tolerance covers the triangulation's O(h^2) s-asymmetry (the
        # cell-diagonal split is not mirror-invariant)
        assert max(abs(r['CF2_pipe']) for r in by_alpha.values()) \
            < 1e-4 * cp_scale, f'CF2 not ~0 at L/D={L}'
        for a in ALPHAS_DEG[(ALPHAS_DEG > 0) & (ALPHAS_DEG < 90.0)]:
            for name in ('CP', 'CF1', 'CQ', 'CM'):
                lo, hi = by_alpha[-a][f'{name}_pipe'], by_alpha[a][f'{name}_pipe']
                scale = max(abs(v) for r in by_alpha.values()
                            for v in [r[f'{name}_pipe']])
                scale = max(scale, 1e-6 * cp_scale)
                worst = max(worst, abs(hi - lo) / scale)
    # tolerance: the JFH file stores DCMs to 6 significant digits (and
    # positions to 9), so mirrored poses reproduce to ~1e-6 relative;
    # a convention error would show up as O(1).
    assert worst < 1e-5, f'mirror symmetry violated: {worst:.3g}'
    return worst


def plot_coefficients(rows, out_dir):
    style_note = 'solid + markers: pipeline    dashed: Cai 2016 reference'
    labels = {'CP': r'$C_P$', 'CF1': r'$C_{F1}$', 'CF2': r'$C_{F2}$',
              'CQ': r'$C_Q$', 'CM': r'$C_M$', 's_cc': r'$s_{cc}$'}
    for name in COEFF_NAMES:
        fig, ax = plt.subplots(figsize=(7, 4.5))
        for color, L in zip(PALETTE, L_OVER_D):
            sub = sorted((r for r in rows if r['L_over_D'] == L
                          and abs(r['alpha_deg']) < 90.0),
                         key=lambda r: r['alpha_deg'])
            a = [r['alpha_deg'] for r in sub]
            ax.plot(a, [r[f'{name}_pipe'] for r in sub], '-o', color=color,
                    lw=2, ms=4, label=f'L/D = {L:g}')
            ax.plot(a, [r[f'{name}_ref'] for r in sub], '--', color=color,
                    lw=2)
            ax.annotate(f'{L:g}', (a[-1], sub[-1][f'{name}_pipe']),
                        textcoords='offset points', xytext=(6, 0),
                        color=color, fontsize=8, va='center')
        ax.axhline(0.0, color='0.85', lw=0.8, zorder=0)
        ax.set_xlabel(r'$\alpha$ (deg), 0 = head-on')
        ax.set_ylabel(labels[name])
        ax.set_title(f'Plate-averaged {labels[name]} vs approach angle\n'
                     f'{style_note}', fontsize=10)
        ax.set_xticks(np.arange(-90, 91, 30))
        ax.legend(fontsize=8, title='distance', title_fontsize=8)
        fig.savefig(out_dir / f'coeff_{name}.png', dpi=200,
                    bbox_inches='tight')
        plt.close(fig)


def plot_peaks(rows, out_dir):
    quantities = [('peak_Cp', r'peak $C_p$'),
                  ('peak_Cshear', r'peak $|C_f|$'),
                  ('peak_Cq', r'peak $C_q$')]
    fig, axes = plt.subplots(3, 1, figsize=(7, 9), sharex=True)
    for ax, (key, label) in zip(axes, quantities):
        for color, L in zip(PALETTE, L_OVER_D):
            sub = sorted((r for r in rows if r['L_over_D'] == L
                          and abs(r['alpha_deg']) < 90.0),
                         key=lambda r: r['alpha_deg'])
            ax.plot([r['alpha_deg'] for r in sub], [r[key] for r in sub],
                    '-o', color=color, lw=2, ms=4, label=f'L/D = {L:g}')
        ax.set_ylabel(label)
        ax.set_yscale('log')
    axes[0].legend(fontsize=8, title='distance', title_fontsize=8)
    axes[0].set_title('Peak per-face coefficients vs approach angle '
                      '(pipeline)', fontsize=10)
    axes[-1].set_xlabel(r'$\alpha$ (deg), 0 = head-on')
    axes[-1].set_xticks(np.arange(-90, 91, 30))
    fig.savefig(out_dir / 'peaks.png', dpi=200, bbox_inches='tight')
    plt.close(fig)


def main(write_vtk=True):
    t_start = time.perf_counter()
    jfh, tv, vv, me = load_case()
    n_firings = len(jfh.JFH)
    assert n_firings == len(ALPHAS_DEG) * len(L_OVER_D), (
        f'unexpected sweep JFH length {n_firings}; regenerate with '
        'case/plume/plume_inclined_plate/jfh/generate_sweep_jfh.py')

    target = tv.mesh
    normals = target.get_unit_normals()
    centroids = compute_face_centroids(target.vectors)
    areas = face_areas(target.vectors)
    tau_face = (centroids - PLATE_CENTER) @ TANGENT_TAU

    if write_vtk:
        VTK_DIR.mkdir(parents=True, exist_ok=True)
    pvd_entries = {}   # L/D -> [(alpha_deg, relative vtu path)]

    print(f'reference curves: {len(set(abs(ALPHAS_DEG)))} angles x '
          f'{len(L_OVER_D)} distances (Eq. 15 quadrature) ...')
    t0 = time.perf_counter()
    ref_cache = reference_rows()
    t_ref = time.perf_counter() - t0
    print(f'  done in {t_ref:.1f} s')

    rows = []
    t0 = time.perf_counter()
    for i in range(n_firings):
        L = L_OVER_D[i // len(ALPHAS_DEG)]
        alpha_deg = float(ALPHAS_DEG[i % len(ALPHAS_DEG)])
        step = {'thrusters': jfh.JFH[i]['thrusters'],
                'xyz': np.array(jfh.JFH[i]['xyz']),
                'dcm': np.array(jfh.JFH[i]['dcm']),
                't': float(jfh.JFH[i]['t'])}
        t_f = time.perf_counter()
        result = compute_plume_strikes(target, normals, vv, step, me,
                                       face_centroids=centroids)
        dt = time.perf_counter() - t_f

        coeffs, peaks, face_fields = pipeline_row(
            result, centroids, normals, areas, tau_face, step['xyz'],
            alpha_deg)
        ref = ref_cache[(abs(alpha_deg), L)]
        row = {'alpha_deg': alpha_deg, 'L_over_D': L,
               'alpha_paper_deg': 90.0 - abs(alpha_deg),
               'wall_time_s': dt, **peaks}
        for name in COEFF_NAMES:
            row[f'{name}_pipe'] = coeffs[name]
            row[f'{name}_ref'] = float(ref[name])
        rows.append(row)

        if write_vtk:
            base = (f'firing-{i:02d}_a{int(alpha_deg):+03d}'
                    f'_LoD{int(L):02d}')
            write_pose_vtk(target, face_fields, base)
            pvd_entries.setdefault(L, []).append(
                (alpha_deg, f'vtk/{base}.vtu'))
    t_sweep = time.perf_counter() - t0

    # sanity: report the edge-on poses (strike membership is
    # epsilon-arbitrary there, see the module docstring); mirror symmetry
    head_on = {r['L_over_D']: r['CP_pipe'] for r in rows
               if r['alpha_deg'] == 0.0}
    for r in rows:
        if abs(r['alpha_deg']) == 90.0:
            print(f"edge-on alpha={r['alpha_deg']:+.0f}, "
                  f"L/D={r['L_over_D']:g}: {r['n_struck']} faces pass the "
                  f"epsilon-degenerate facing test; CP="
                  f"{r['CP_pipe']:.3e} (head-on "
                  f"{head_on[r['L_over_D']]:.3e}), peak Cp="
                  f"{r['peak_Cp']:.3e}, peak |Cf|={r['peak_Cshear']:.3e}")
    worst = check_mirror_symmetry(rows)
    print(f'mirror-symmetry check: worst normalized asymmetry {worst:.2e}')

    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    columns = list(rows[0].keys())
    csv_path = RESULTS_DIR / 'sweep_coefficients.csv'
    with open(csv_path, 'w', encoding='utf-8', newline='') as fh:
        writer = csv.DictWriter(fh, fieldnames=columns)
        writer.writeheader()
        writer.writerows(rows)
    print(f'wrote {csv_path}')

    plot_coefficients(rows, RESULTS_DIR)
    plot_peaks(rows, RESULTS_DIR)
    print(f'wrote coefficient and peak plots to {RESULTS_DIR}')

    if write_vtk:
        for L, entries in pvd_entries.items():
            write_pvd(RESULTS_DIR / f'sweep_LoD{int(L):02d}.pvd', entries)
        print(f'wrote {n_firings} per-pose VTK files to {VTK_DIR} '
              f'(+ {len(pvd_entries)} sweep_LoD*.pvd collections in '
              f'{RESULTS_DIR})')

    n_faces = len(target.vectors)
    print(f'timings: {n_firings} firings x {n_faces} faces -- sweep '
          f'{t_sweep:.1f} s ({t_sweep / n_firings * 1e3:.0f} ms/firing), '
          f'reference {t_ref:.1f} s, total '
          f'{time.perf_counter() - t_start:.1f} s')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument('--no-vtk', action='store_true',
                        help='skip the per-pose VTK export (CSV + plots '
                             'only)')
    args = parser.parse_args()
    main(write_vtk=not args.no_vtk)
