"""Generate the sweep JFH for the cylinder-target smoke case.

Same angle x distance sweep idea as the plate cases, but aimed at a CYLINDER
target (data/stl/cylinder_transformed.stl: radius 2 m, axis along X spanning
x in [-7, 0], centroid C = (-3.5, 0, 0), bounding-sphere radius ~4.03 m).

The plate is replaced by the cylinder; the visiting vehicle (single thruster
at the VV origin, no cant) is still swept. For each firing the VV is placed on
the arc of radius L about the cylinder centroid C, with the thruster axis aimed
at C and the JFH DCM set so the pipeline's plume normal (first column of the
DCM, with the identity TCF) points along that axis:

    d_hat(alpha) = cos(alpha) * n_hat + sin(alpha) * t_hat
    VV position  = C + L * d_hat(alpha),  thruster axis = -d_hat(alpha)

with n_hat = (0, 0, 1) and t_hat = (1, 0, 0), so the sweep orbits the cylinder
in the global X-Z plane (alpha = 0 fires straight down -Z onto the curved
surface; alpha = +/-90 fires along -/+X at the end caps).

The orbit radii all exceed the cylinder's bounding sphere so the VV never sits
inside the target (this case is a pipeline smoke test -- the strike results are
not physically meaningful). Sweep: alpha from -90 to +90 deg in 10 deg steps
(19 angles) x L in {6, 8, 10, 12, 14} m, enumerated distance-major:
firing index = i_L * 19 + i_alpha + 1. 95 firings total, 1.0 s each.

JFH files are always generated by script, never hand-edited. Run from this
directory:  python generate_cylinder_sweep_jfh.py
"""

from pathlib import Path

import numpy as np

from generate_jfh_inclined_plate import write_jfh

OUT_NAME = 'jfh_cylinder_sweep.A'

CYLINDER_CENTER = np.array([-3.5, 0.0, 0.0])
ALPHA0_DEG = 0.0                       # global-frame orbit-plane tilt
ALPHAS_DEG = np.arange(-90.0, 90.0 + 1e-9, 10.0)
RADII = [6.0, 8.0, 10.0, 12.0, 14.0]   # arc radii (m); all > ~4.03 bounding sphere


def pose_for(alpha_deg, L):
    """(vv_position, dcm) for one sweep firing; dcm's first column is the
    thruster axis (see the pipeline's plume-normal convention)."""
    a0 = np.deg2rad(ALPHA0_DEG)
    n_hat = np.array([-np.sin(a0), 0.0, np.cos(a0)])
    t_hat = np.array([np.cos(a0), 0.0, np.sin(a0)])
    alpha = np.deg2rad(alpha_deg)
    d_hat = np.cos(alpha) * n_hat + np.sin(alpha) * t_hat
    position = CYLINDER_CENTER + L * d_hat
    axis = -d_hat                       # aimed at the cylinder centroid
    # right-handed triad; the axis always lies in the X-Z plane, so the
    # global Y axis is a valid second column
    c1 = np.array([0.0, 1.0, 0.0])
    c2 = np.cross(axis, c1)
    dcm = np.column_stack([axis, c1, c2])
    return position, dcm


def dcm_string(dcm):
    return ' '.join(f'{v:.6e}' for v in np.asarray(dcm).ravel())


if __name__ == '__main__':
    firings = []
    for L in RADII:
        for alpha_deg in ALPHAS_DEG:
            position, dcm = pose_for(alpha_deg, L)
            firings.append((0.0, 1.0, dcm_string(dcm), tuple(position), [1]))
    out_path = Path(__file__).resolve().parent / OUT_NAME
    write_jfh(out_path, firings)
    print(f'saved {out_path} ({len(firings)} firings: '
          f'{len(ALPHAS_DEG)} angles x {len(RADII)} radii)')
