"""Generate the single-firing JFH for the Cai 2016 inclined-plate case.

One firing at the paper geometry (Aerospace 2016, 3(4):43, Section 4): the
visiting vehicle sits at the origin with an identity DCM, so its single
thruster (exit at the VV origin, no cant) fires along +X toward the plate
centered at (4, 0, 0) m. Firing time 1.0 s makes heat_flux_load equal the
heat-flux rate.

JFH files are always generated by script, never hand-edited. Run from this
directory:  python generate_jfh_inclined_plate.py
"""

from pathlib import Path

OUT_NAME = 'jfh_plume_inclined_plate.A'

DCM_IDENTITY = ('1.000000e+00 0.000000e+00 0.000000e+00 '
                '0.000000e+00 1.000000e+00 0.000000e+00 '
                '0.000000e+00 0.000000e+00 1.000000e+00')


def write_jfh(path, firings):
    """firings: list of (dt, t, dcm_str, xyz, thrusters)."""
    lines = [f'offseted    {len(firings)}       0', '       0.000       0.000       0.000']
    for n, (dt, t, dcm, xyz, thrusters) in enumerate(firings, start=1):
        xyz_str = ' '.join(f'{v:.9g}' for v in xyz)
        thr_str = ' '.join(str(i) for i in thrusters)
        lines.append(f'      {n} {dt:g} {t:g} 0 {dcm} {xyz_str} 1 '
                     f'{len(thrusters)} {thr_str}')
    with open(path, 'w', newline='\n') as fh:
        fh.write('\n'.join(lines) + '\n')


if __name__ == '__main__':
    out_path = Path(__file__).resolve().parent / OUT_NAME
    write_jfh(out_path, [(0.0, 1.0, DCM_IDENTITY, (0.0, 0.0, 0.0), [1])])
    print(f'saved {out_path}')
